In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
acc = pd.read_csv(r"/content/sample_data/US_Accidents.csv")
acc.head()

<ipython-input-4-2d90f940819a>:1: DtypeWarning: Columns (33,34,35,36,37,38,39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  acc = pd.read_csv(r"/content/sample_data/US_Accidents.csv")

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [ ]:
acc.shape

(14272, 47)

In [ ]:
acc.columns

Index(['ID', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'End_Lat', 'End_Lng', 'Distance(mi)', 'Description', 'Number', 'Street',
       'Side', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [ ]:
acc.isna().sum(axis=0)

ID                           0
Severity                     0
Start_Time                   0
End_Time                     0
Start_Lat                    0
Start_Lng                    0
End_Lat                      0
End_Lng                      0
Distance(mi)                 0
Description                  0
Number                   12126
Street                       0
Side                         0
City                         0
County                       0
State                        0
Zipcode                      6
Country                      0
Timezone                     6
Airport_Code                 7
Weather_Timestamp          134
Temperature(F)             237
Wind_Chill(F)            12259
Humidity(%)                253
Pressure(in)               230
Visibility(mi)             272
Wind_Direction             135
Wind_Speed(mph)           2315
Precipitation(in)        13294
Weather_Condition          245
Amenity                      0
Bump                         0
Crossing                     0
Give_Way                     0
Junction                     0
No_Exit                      0
Railway                      0
Roundabout                   0
Station                      0
Stop                         0
Traffic_Calming              0
Traffic_Signal               0
Turning_Loop                 0
Sunrise_Sunset               0
Civil_Twilight               0
Nautical_Twilight            0
Astronomical_Twilight        1
dtype: int64

In [ ]:
acc['Precipitation(in)'].describe()

count    978.000000
mean       0.015419
std        0.040724
min        0.000000
25%        0.000000
50%        0.000000
75%        0.010000
max        0.370000
Name: Precipitation(in), dtype: float64

In [ ]:
acc['Severity'].describe()

count    14272.000000
mean         2.258268
std          0.546873
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          4.000000
Name: Severity, dtype: float64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243737 entries, 0 to 243736
Data columns (total 47 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     243737 non-null  object
 1   Severity               243737 non-null  int64
 2   Start_Time             243737 non-null  object
 3   End_Time               243737 non-null  object
 4   Start_Lat              243737 non-null  float64
 5   Start_Lng              243737 non-null  float64
 6   End_Lat                243737 non-null  float64
 7   End_Lng                243737 non-null  float64
 8   Distance(mi)           243737 non-null  float64
 9   Description            243737 non-null  object
 10  Number                 53260 non-null   float64
 11  Street                 243736 non-null  object
 12  Side                   243736 non-null  object
 13  City                   243714 non-null  object
 14  County                 243736 non-null  object
 15  State                  243736 non-null  object
 16  Zipcode                243586 non-null  object
 17  Country                243736 non-null  object
 18  Timezone               243557 non-null  object
 19  Airport_Code           243295 non-null  object
 20  Weather_Timestamp      241246 non-null  object
 21  Temperature(F)         238555 non-null  float64
 22  Wind_Chill(F)          51650 non-null   float64
 23  Humidity(%)            238280 non-null  float64
 24  Pressure(in)           239604 non-null  float64
 25  Visibility(mi)         237825 non-null  float64
 26  Wind_Direction         241046 non-null  object
 27  Wind_Speed(mph)        205982 non-null  float64
 28  Precipitation(in)      45302 non-null   float64
 29  Weather_Condition      237891 non-null  object
 30  Amenity                243736 non-null  object
 31  Bump                   243736 non-null  object
 32  Crossing               243736 non-null  object
 33  Give_Way               243736 non-null  object
 34  Junction               243736 non-null  object
 35  No_Exit                243736 non-null  object
 36  Railway                243736 non-null  object
 37  Roundabout             243736 non-null  object
 38  Station                243736 non-null  object
 39  Stop                   243736 non-null  object
 40  Traffic_Calming        243736 non-null  object
 41  Traffic_Signal         243736 non-null  object
 42  Turning_Loop           243736 non-null  object
 43  Sunrise_Sunset         243675 non-null  object
 44  Civil_Twilight         243675 non-null  object
 45  Nautical_Twilight      243675 non-null  object
 46  Astronomical_Twilight  243675 non-null  object
dtypes: float64(13), int64(1), object(33)
memory usage: 87.4+ MB

In [ ]:
incident_details = acc[['ID', 'Severity', 'Start_Time', 'End_Time', 'Description']]

# Location
location = acc[['Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Number', 'Street', 'Side', 'City', 'County', 'State', 'Zipcode', 'Country']]

# Time and Timezone
time_and_timezone = acc[['Timezone']]

# Weather and Environmental Conditions
weather_conditions = acc[['Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition']]

# Road Features
road_features = acc[['Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop']]

# Day/Night Information
day_night_info = acc[['Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight']]

In [ ]:
print("Incident Details:")
print(incident_details.head())

Incident Details:
    ID  Severity           Start_Time             End_Time  \
0  A-1         3  2016-02-08 00:37:08  2016-02-08 06:37:08
1  A-2         2  2016-02-08 05:56:20  2016-02-08 11:56:20
2  A-3         2  2016-02-08 06:15:39  2016-02-08 12:15:39
3  A-4         2  2016-02-08 06:51:45  2016-02-08 12:51:45
4  A-5         3  2016-02-08 07:53:43  2016-02-08 13:53:43

                                         Description
0  Between Sawmill Rd/Exit 20 and OH-315/Olentang...
1                 At OH-4/OH-235/Exit 41 - Accident.
2                   At I-71/US-50/Exit 1 - Accident.
3                    At Dart Ave/Exit 21 - Accident.
4                 At Mitchell Ave/Exit 6 - Accident.

In [ ]:
incident_details['Severity'].describe()

count    90946.000000
mean         2.452466
std          0.708897
min          2.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          4.000000
Name: Severity, dtype: float64

In [ ]:
print("location:")
print(location.head())

location:
   Start_Lat  Start_Lng    End_Lat    End_Lng  Distance(mi)  Number  \
0  40.108910 -83.092860  40.112060 -83.031870         3.230     NaN
1  39.865420 -84.062800  39.865010 -84.048730         0.747     NaN
2  39.102660 -84.524680  39.102090 -84.523960         0.055     NaN
3  41.062130 -81.537840  41.062170 -81.535470         0.123     NaN
4  39.172393 -84.492792  39.170476 -84.501798         0.500     NaN

        Street Side        City      County State Zipcode Country
0  Outerbelt E    R      Dublin    Franklin    OH   43017      US
1       I-70 E    R      Dayton  Montgomery    OH   45424      US
2       I-75 S    R  Cincinnati    Hamilton    OH   45203      US
3       I-77 N    R       Akron      Summit    OH   44311      US
4       I-75 S    R  Cincinnati    Hamilton    OH   45217      US

In [ ]:
location.isna().sum(axis = 0 )

Start_Lat           0
Start_Lng           0
End_Lat             0
End_Lng             0
Distance(mi)        0
Number          71847
Street              0
Side                0
City               14
County              0
State               0
Zipcode            54
Country             0
dtype: int64

In [ ]:
missingData_location = location.isna().sum().sort_values(ascending=False)/len(location)
missingData_location

Number          0.789996
Zipcode         0.000594
City            0.000154
Start_Lat       0.000000
Start_Lng       0.000000
End_Lat         0.000000
End_Lng         0.000000
Distance(mi)    0.000000
Street          0.000000
Side            0.000000
County          0.000000
State           0.000000
Country         0.000000
dtype: float64

In [ ]:
location = location.drop(['Number'], axis = 1)
location

,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,Side,City,County,State,Zipcode,Country
0,40.108910,-83.092860,40.112060,-83.031870,3.230,Outerbelt E,R,Dublin,Franklin,OH,43017,US
1,39.865420,-84.062800,39.865010,-84.048730,0.747,I-70 E,R,Dayton,Montgomery,OH,45424,US
2,39.102660,-84.524680,39.102090,-84.523960,0.055,I-75 S,R,Cincinnati,Hamilton,OH,45203,US
3,41.062130,-81.537840,41.062170,-81.535470,0.123,I-77 N,R,Akron,Summit,OH,44311,US
4,39.172393,-84.492792,39.170476,-84.501798,0.500,I-75 S,R,Cincinnati,Hamilton,OH,45217,US
...,...,...,...,...,...,...,...,...,...,...,...,...
90941,41.178160,-96.102660,41.178160,-96.102660,0.000,W Giles Rd,L,La Vista,Sarpy,NE,68128,US
90942,42.449790,-94.613673,42.449912,-94.630589,0.862,US-20 W,R,Rockwell City,Calhoun,IA,50579,US
90943,41.223270,-95.997260,41.223890,-96.009520,0.639,I-80 W,R,Omaha,Douglas,NE,68106,US
90944,41.190760,-96.023830,41.190660,-96.023830,0.007,S 72nd St,R,La Vista,Sarpy,NE,68128,US
90945,41.190730,-96.043080,41.190730,-96.042920,0.008,Harrison St,L,La Vista,Sarpy,NE,68128-2919,US

Warning: total number of rows (90946) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: total number of rows (90946) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
missingData_location = location.isna().sum().sort_values(ascending=False)/len(location)
missingData_location

Zipcode         0.000594
City            0.000154
Start_Lat       0.000000
Start_Lng       0.000000
End_Lat         0.000000
End_Lng         0.000000
Distance(mi)    0.000000
Street          0.000000
Side            0.000000
County          0.000000
State           0.000000
Country         0.000000
dtype: float64

In [ ]:
rows_with_nan_zipcode = location[location['Zipcode'].isna()]
rows_with_nan_zipcode

,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,Side,City,County,State,Zipcode,Country
1102,37.942090,-122.475470,37.942064,-122.475324,0.008,Richmond-San Rafael Brg,R,Ross Valley,Marin,CA,NaN,US
1389,37.933100,-122.414470,37.942140,-122.474760,3.344,Richmond-San Rafael Brg,R,West Contra Costa,Contra Costa,CA,NaN,US
2222,37.933100,-122.414470,37.942140,-122.474760,3.344,Richmond-San Rafael Brg,R,West Contra Costa,Contra Costa,CA,NaN,US
2579,37.932770,-122.409590,37.942600,-122.477610,3.768,Richmond-San Rafael Brg,R,West Contra Costa,Contra Costa,CA,NaN,US
4489,37.934945,-122.442183,37.934077,-122.429174,0.711,Richmond-San Rafael Brg,R,Ross Valley,Marin,CA,NaN,US
5205,37.932770,-122.409590,37.942600,-122.477610,3.768,Richmond-San Rafael Brg,R,West Contra Costa,Contra Costa,CA,NaN,US
31740,38.990740,-76.371660,38.983330,-76.340040,1.774,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
31902,45.795489,-68.428530,45.636546,-68.501838,11.537,I-95 S,R,North Penobscot,Penobscot,ME,NaN,US
33143,38.991890,-76.371090,39.008300,-76.403690,2.086,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
33907,27.919383,-82.610631,27.936060,-82.563990,3.072,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
35017,38.990740,-76.371660,38.983330,-76.340040,1.774,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
35385,38.990740,-76.371660,38.983330,-76.340040,1.774,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
35941,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
36499,39.000970,-76.398530,39.008300,-76.403690,0.577,William Preston Lane Jr Memorial Brg,R,District 5,Anne Arundel,MD,NaN,US
38288,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
38300,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
38429,26.145700,-80.466330,26.145720,-80.465890,0.027,Alligator Aly E,R,Conservation,Broward,FL,NaN,US
39166,26.172840,-80.879300,26.172804,-80.880990,0.105,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
39326,38.984907,-76.341219,38.991890,-76.371090,1.675,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
40886,38.991890,-76.371090,39.015294,-76.408202,2.566,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
41974,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
42608,37.045455,-76.063531,37.034211,-76.080249,1.206,US-13 N,R,District 1,Northampton,VA,NaN,US
44588,30.067706,-90.390133,30.066033,-90.387663,0.188,I-10 E,R,District 6,St. Charles,LA,NaN,US
46317,26.162556,-80.804555,26.158851,-80.780682,1.502,Alligator Aly E,R,Conservation,Broward,FL,NaN,US
46751,30.196206,-90.123160,30.218014,-90.119320,1.524,Lake Pontchartrain Cswy,R,District 10,St. Tammany,LA,NaN,US
47158,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
48117,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
53556,26.146200,-80.466420,26.146200,-80.466420,0.000,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
54696,27.919384,-82.610631,27.936060,-82.563990,3.072,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
56796,27.919383,-82.610631,27.936060,-82.563990,3.072,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
61331,26.154814,-80.754639,26.146183,-80.601602,9.510,Alligator Aly E,R,Conservation,Broward,FL,NaN,US
63049,26.172840,-80.879300,26.172736,-80.884331,0.312,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
63270,38.991890,-76.371090,39.008300,-76.403690,2.086,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
63273,38.984460,-76.339310,38.991890,-76.371090,1.782,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
64253,38.990740,-76.371660,38.983330,-76.340040,1.774,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
66160,26.170060,-80.851100,26.171780,-80.862220,0.700,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
68869,26.146200,-80.466420,26.146190,-80.467590,0.073,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
69061,27.923017,-82.600526,27.923017,-82.600526,0.000,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
74921,26.170060,-80.851100,26.154800,-81.351050,31.022,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
76410,27.919706,-82.609779,27.936060,-82.563990,3.015,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
77072,26.170870,-80.856310,26.170870,-80.856308,0.000,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
78254,27.919706,-82.609779,27.936060,-82.563990,3.015,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
78312,27.912995,-82.623563,27.927890,-82.586860,2.466,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
79429,30.134121,-90.134048,30.185194,-90.125094,3.569,Lake Pontchartrain Cswy,R,District 5,Jefferson,LA,NaN,US
81099,26.172840,-80.879300,26.172820,-80.880230,0.058,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
81148,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US
83162,38.987230,-76.351190,38.991890,-76.371090,1.116,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
84641,26.170060,-80.851100,26.171780,-80.862220,0.700,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
84682,26.170060,-80.851100,26.171780,-80.862220,0.700,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
85015,26.170060,-80.851100,26.154800,-81.351050,31.022,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
86347,37.937726,-75.381385,37.943280,-75.453650,3.956,Chincoteague Rd,R,District 1,Accomack,VA,NaN,US
86704,26.146150,-80.584181,26.146130,-80.572380,0.732,I-75 S,R,Conservation,Broward,FL,NaN,US
90256,26.170870,-80.856310,26.170870,-80.856310,0.000,Everglades Pkwy W,R,Conservation,Broward,FL,NaN,US
90317,27.919710,-82.609770,27.936060,-82.563990,3.014,Howard Frankland Brg,R,St. Petersburg,Pinellas,FL,NaN,US

In [ ]:

location['Zipcode'] = location.groupby('County')['Zipcode'].fillna(method='ffill')
location['Zipcode']

0             43017
1             45424
2             45203
3             44311
4             45217
            ...
90941         68128
90942         50579
90943         68106
90944         68128
90945    68128-2919
Name: Zipcode, Length: 90946, dtype: object

In [ ]:
ll = location['Zipcode'].isna().sum()
ll

3

In [ ]:
rows_with_nan_zipcode = location[location['Zipcode'].isna()]
rows_with_nan_zipcode

,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,Side,City,County,State,Zipcode,Country
31740,38.99074,-76.37166,38.98333,-76.34004,1.774,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
33143,38.99189,-76.37109,39.00830,-76.40369,2.086,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US
35017,38.99074,-76.37166,38.98333,-76.34004,1.774,William Preston Lane Jr Memorial Brg,R,District 4 Kent Island,Queen Anne's,MD,NaN,US

In [ ]:
missingData_location = location.isna().sum().sort_values(ascending=False)/len(location)
missingData_location

City            0.000154
Zipcode         0.000033
Start_Lat       0.000000
Start_Lng       0.000000
End_Lat         0.000000
End_Lng         0.000000
Distance(mi)    0.000000
Street          0.000000
Side            0.000000
County          0.000000
State           0.000000
Country         0.000000
dtype: float64

In [ ]:
location['Zipcode'] = location.groupby('County')['Zipcode'].fillna(method='ffill')
location['Zipcode'].fillna(21670, inplace=True)

In [ ]:
missingData_location = location.isna().sum().sort_values(ascending=False)/len(location)
missingData_location

City            0.000154
Start_Lat       0.000000
Start_Lng       0.000000
End_Lat         0.000000
End_Lng         0.000000
Distance(mi)    0.000000
Street          0.000000
Side            0.000000
County          0.000000
State           0.000000
Zipcode         0.000000
Country         0.000000
dtype: float64

In [ ]:

rows_with_nan_city = location[location['City'].isna()]
rows_with_nan_city

,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,Side,City,County,State,Zipcode,Country
34903,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US
43106,40.84309,-84.802360,40.844250,-84.784350,0.945,N 700 E,R,NaN,Adams,IN,45874,US
43114,40.84309,-84.802360,40.844250,-84.784350,0.945,N 700 E,R,NaN,Adams,IN,45874,US
43248,40.84309,-84.802360,40.841207,-84.841024,2.025,N 700 E,R,NaN,Adams,IN,45874,US
55225,41.03674,-73.675490,41.037639,-73.674930,0.069,King St,R,NaN,Westchester,NY,06831,US
60362,38.87568,-76.931430,38.876020,-76.930990,0.033,Southern Ave,R,NaN,District of Columbia,DC,20743,US
60682,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US
63025,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US
68702,27.38876,-82.449383,27.388760,-82.449383,0.000,University Pkwy,R,NaN,Sarasota,FL,34201,US
68712,27.38876,-82.449556,27.388760,-82.449556,0.000,University Pkwy,R,NaN,Sarasota,FL,34201,US
71720,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US
73835,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US
76977,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US
88533,41.03674,-73.675490,41.083450,-73.665300,3.271,King St,R,NaN,Westchester,NY,06831,US

In [ ]:
location['City'] = location.groupby('County')['City'].fillna(method='ffill')
# location['Zipcode'].fillna(21670, inplace=True)

In [ ]:
missingData_location = location.isna().sum().sort_values(ascending=False)/len(location)
missingData_location

Start_Lat       0.0
Start_Lng       0.0
End_Lat         0.0
End_Lng         0.0
Distance(mi)    0.0
Street          0.0
Side            0.0
City            0.0
County          0.0
State           0.0
Zipcode         0.0
Country         0.0
dtype: float64